Update patch set 11
Patch Set 11: Code-Review-1

please leverage pep8 check, so many violations:
pep8 runtests: commands[0] | flake8 /Users/serena/opnfv/releng-testresults/testapi/testapi-client
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/git.py:277:13: W503 line break before binary operator
            and not os.access(new_changelog, os.W_OK)):
            ^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/git.py:300:13: W503 line break before binary operator
            and not os.access(new_authors, os.W_OK)):
            ^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/options.py:52:14: W503 line break before binary operator
             and option_dict[option_name][1].lower() in TRUE_VALUES) or
             ^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/packaging.py:61:13: W503 line break before binary operator
            + list(REQUIREMENTS_FILES))
            ^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/packaging.py:276:1: E305 expected 2 blank lines after class or function definition, found 1
_wsgi_text = """#PBR Generated from %(group)r
^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/packaging.py:540:1: E305 expected 2 blank lines after class or function definition, found 1
try:
^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/version.py:326:17: W503 line break before binary operator
                and pre_separator is None):
                ^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/tests/test_packaging.py:645:9: E731 do not assign a lambda expression, use a def
        get_kwargs = lambda tag: packaging._get_increment_kwargs(git_dir, tag)
        ^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/tests/test_setup.py:100:14: W503 line break before binary operator
             or self.env_value is not None))
             ^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/tests/test_setup.py:102:1: E305 expected 2 blank lines after class or function definition, found 1
_changelog_content = """7780758\x00Break parser\x00 (tag: refs/tags/1_foo.1)
^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/tests/test_setup.py:131:1: E305 expected 2 blank lines after class or function definition, found 1
_old_git_changelog_content = '\n'.join(
^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/tests/testpackage/doc/source/conf.py:25:5: E265 block comment should start with '# '
    #'sphinx.ext.intersphinx',
    ^
/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.eggs/pbr-3.1.1-py2.7.egg/pbr/tests/testpackage/doc/source/conf.py:74:1: E265 block comment should start with '# '
#intersphinx_mapping = {'http://docs.python.org/': None}
^
ERROR: InvocationError: '/Users/serena/opnfv/releng-testresults/testapi/testapi-client/.tox/pep8/bin/flake8 /Users/serena/opnfv/releng-testresults/testapi/testapi-client'
____________________________________________________________________ summary ____________________________________________________________________
ERROR:   pep8: commands failed

Patch-set: 11
Label: Code-Review=-1